name: Deploy Azure Function

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: .NET Restore
        run: dotnet restore

      - name: .NET Build
        run: dotnet build --configuration Release

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure Functions Core Tools
        run: npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Set Function App Settings
        run: |
          echo "${{ secrets.FUNCTION_APP_SETTINGS }}" > functionapp-settings.json
          SETTINGS_JSON=$(cat functionapp-settings.json)
          for key in $(echo "$SETTINGS_JSON" | jq -r 'keys[]'); do
            value=$(echo "$SETTINGS_JSON" | jq -r --arg k "$key" '.[$k]')
            az functionapp config appsettings set --name ${{ secrets.FUNCTION_APP_NAME }} --resource-group ${{ secrets.FUNCTION_APP_RG }} --settings "$key=$value"
          done
        env:
          FUNCTION_APP_SETTINGS: ${{ secrets.FUNCTION_APP_SETTINGS }}

      - name: Deploy Azure Function
      
        run: |
          cd ./fiap.soat.fastfood.serverless.function/
          func azure functionapp publish ${{ secrets.FUNCTION_APP_NAME }} --csharp
