name: Deploy Azure Function

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: .NET Build
        run: dotnet build --configuration Release
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Function App Settings
        run: |
          cat > functionapp-settings.json <<'EOF' 
          ${{ secrets.FUNCTION_APP_SETTINGS }} 
          EOF

          if ! jq empty functionapp-settings.json > /dev/null 2>&1; then
            echo "❌ Error: Invalid JSON in FUNCTION_APP_SETTINGS secret"
            exit 1
          fi

          echo "Applying Application Settings..."
          for key in $(jq -r 'keys[]' functionapp-settings.json); do
            value=$(jq -r --arg k "$key" '.[$k]' functionapp-settings.json)
            az functionapp config appsettings set \
              --name ${{ secrets.FUNCTION_APP_NAME }} \
              --resource-group ${{ secrets.FUNCTION_APP_RG }} \
              --settings "$key=$value"
          done

          echo "✅ Application Settings configured successfully."
        env:
          FUNCTION_APP_SETTINGS: ${{ secrets.FUNCTION_APP_SETTINGS }}

      - name: Publish
        run: dotnet publish ./fiap.soat.fastfood.serverless.function/fiap.soat.fastfood.serverless.function.csproj --configuration Release --output ./publish --no-build

      - name: Deploy Azure Function
        run: |
          cd "./publish"
          zip -r ../function.zip . > /dev/null
          cd ..

          # Aplica o deploy via Azure CLI
          az functionapp deployment source config-zip \
            --name ${{ secrets.FUNCTION_APP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --src function.zip > /dev/null

          echo "✅ Deploy concluído com sucesso."
