name: Deploy Azure Function

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: .NET Restore
        run: dotnet restore

      - name: .NET Build
        run: dotnet build --configuration Release

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure Functions Core Tools
        run: npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Set Function App Settings
        run: |
          cat > functionapp-settings.json <<'EOF' 
          ${{ secrets.FUNCTION_APP_SETTINGS }} 
          EOF

          if ! jq empty functionapp-settings.json > /dev/null 2>&1; then
            echo "❌ Error: Invalid JSON in FUNCTION_APP_SETTINGS secret"
            exit 1
          fi

          echo "Applying Application Settings..."
          for key in $(jq -r 'keys[]' functionapp-settings.json); do
            value=$(jq -r --arg k "$key" '.[$k]' functionapp-settings.json)
            az functionapp config appsettings set \
              --name ${{ secrets.FUNCTION_APP_NAME }} \
              --resource-group ${{ secrets.FUNCTION_APP_RG }} \
              --settings "$key=$value"
          done

          echo "✅ Application Settings configured successfully."
        env:
          FUNCTION_APP_SETTINGS: ${{ secrets.FUNCTION_APP_SETTINGS }}

      - name: Deploy Azure Function
      
        run: |
          cd ./fiap.soat.fastfood.serverless.function/
          func azure functionapp publish ${{ secrets.FUNCTION_APP_NAME }} --csharp --force
